language: java
script: 
  - "mvn -N io.takari:maven:wrapper"
  - "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
sudo:
  true
jdk:
  openjdk11
branches:
  only:
  - master
  - 0.2-alpha
before_install:
  - chmod +x mvnw