spring:
  profiles:
    active: dev
    
#不在此处理https,建议使用nginx
  #ssl:
    #在jdk目录下使用keytool.命令如下:
    #.\keytool.exe -genkey -alias Frodez -keyalg RSA -keysize 2048 -keypass 
    #Frodez -keystore https.keystore -storepass 123456 -validity 3650 
    #-dname "cn=Frodez,ou=Frodez,o=beijing,l=beijing,st=beijing,c=cn"
    #enabled: true
    #key-store: classpath:settings/https.jks
    #key-store-password: 123456
    #key-password: 123456