logging:
  config: classpath:settings/log.xml

mapper:
  identity: MYSQL
  mappers: frodez.config.mybatis.DataMapper
  
mybatis:
  mapper-locations: classpath:frodez/service/*Mapper.xml
  type-aliases-package: frodez.dao.model
  
pagehelper:
  helperDialect: mysql
  params: count=countSql
  pageSizeZero: true
  supportMethodsArguments: true
  
server:
  port: 9090
  #不在此处理https
  #ssl:
    #在jdk目录下使用keytool.命令如下:
    #.\keytool.exe -genkey -alias Frodez -keyalg RSA -keysize 2048 -keypass 
    #Frodez -keystore https.keystore -storepass 123456 -validity 3650 
    #-dname "cn=Frodez,ou=Frodez,o=beijing,l=beijing,st=beijing,c=cn"
    #enabled: true
    #key-store: classpath:settings/https.jks
    #key-store-password: 123456
    #key-password: 123456
  servlet:
    context-path: /api
  http2:
    enabled: true
    
spring:
  profiles:
    active: dev
  resources:
    add-mappings: true
  aop:
    auto: true
    proxy-target-class: true
  data:
    redis:
      repositories:
        enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: frodez
    password: 123456
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    generator:
      WRITE_BIGDECIMAL_AS_PLAIN: true
    parser:
      ALLOW_UNQUOTED_CONTROL_CHARS: true  
  redis:
    database: 0
    host: 127.0.0.1
    password: ''
    port: 6379
    timeout: 60000
    lettuce:
      pool:
        max-active: -1
        max-wait: 45000
        max-idle: -1
        min-idle: 10